export const GET_PHUC_LOI_TUYEN_DUNG = "GET_PHUC_LOI_TUYEN_DUNG"
export const GET_PHUC_LOI_TUYEN_DUNG_SUCCESS = "GET_PHUC_LOI_TUYEN_DUNG_SUCCESS"
export const GET_PHUC_LOI_TUYEN_DUNG_FAIL = "GET_PHUC_LOI_TUYEN_DUNG_FAIL"

export const ADD_PHUC_LOI_TUYEN_DUNG = "ADD_PHUC_LOI_TUYEN_DUNG"
export const ADD_PHUC_LOI_TUYEN_DUNG_SUCCESS = "ADD_PHUC_LOI_TUYEN_DUNG_SUCCESS"
export const ADD_PHUC_LOI_TUYEN_DUNG_FAIL = "ADD_PHUC_LOI_TUYEN_DUNG_FAIL"

export const DELETE_PHUC_LOI_TUYEN_DUNG = "DELETE_PHUC_LOI_TUYEN_DUNG"
export const DELETE_PHUC_LOI_TUYEN_DUNG_SUCCESS = "DELETE_PHUC_LOI_TUYEN_DUNG_SUCCESS"
export const DELETE_PHUC_LOI_TUYEN_DUNG_FAIL = "DELETE_PHUC_LOI_TUYEN_DUNG_FAIL"

export const UPDATE_PHUC_LOI_TUYEN_DUNG = "UPDATE_PHUC_LOI_TUYEN_DUNG"
export const UPDATE_PHUC_LOI_TUYEN_DUNG_SUCCESS = "UPDATE_PHUC_LOI_TUYEN_DUNG_SUCCESS"
export const UPDATE_PHUC_LOI_TUYEN_DUNG_FAIL = "UPDATE_PHUC_LOI_TUYEN_DUNG_FAIL"

export const SEARCH_PHUC_LOI_TUYEN_DUNG = "SEARCH_PHUC_LOI_TUYEN_DUNG"
export const SEARCH_PHUC_LOI_TUYEN_DUNG_SUCCESS = "SEARCH_PHUC_LOI_TUYEN_DUNG_SUCCESS"
export const SEARCH_PHUC_LOI_TUYEN_DUNG_FAIL = "SEARCH_PHUC_LOI_TUYEN_DUNG"



