export const GET_TAI_KHOAN = "GET_TAI_KHOAN"
export const GET_TAI_KHOAN_SUCCESS = "GET_TAI_KHOAN_SUCCESS"
export const GET_TAI_KHOAN_FAIL = "GET_TAI_KHOAN_FAIL"

export const UPDATE_TAI_KHOAN = "UPDATE_TAI_KHOAN"
export const UPDATE_TAI_KHOAN_SUCCESS = "UPDATE_TAI_KHOAN_SUCCESS"
export const UPDATE_TAI_KHOAN_FAIL = "UPDATE_TAI_KHOAN_FAIL"


