export const GET_ALL_VIDEO = "GET_ALL_VIDEO"
export const GET_ALL_VIDEO_SUCCESS = "GET_ALL_VIDEO_SUCCESS"
export const GET_ALL_VIDEO_FAIL = "GET_ALL_VIDEO_FAIL"

export const POST_VIDEO = "POST_VIDEO"
export const POST_VIDEO_SUCCESS = "POST_VIDEO_SUCCESS"
export const POST_VIDEO_FAIL = "POST_VIDEO_FAIL"

export const DELETE_VIDEO = "DELETE_VIDEO"
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS"
export const DELETE_VIDEO_FAIL = "DELETE_VIDEO_FAIL"





