export const GET_UNG_TUYEN_NGAY = "GET_UNG_TUYEN_NGAY"
export const GET_UNG_TUYEN_NGAY_SUCCESS = "GET_UNG_TUYEN_NGAY_SUCCESS"
export const GET_UNG_TUYEN_NGAY_FAIL = "GET_UNG_TUYEN_NGAY_FAIL"

export const ADD_UNG_TUYEN_NGAY = "ADD_UNG_TUYEN_NGAY"
export const ADD_UNG_TUYEN_NGAY_SUCCESS = "ADD_UNG_TUYEN_NGAY_SUCCESS"
export const ADD_UNG_TUYEN_NGAY_FAIL = "ADD_UNG_TUYEN_NGAY_FAIL"

export const DELETE_UNG_TUYEN_NGAY = "DELETE_UNG_TUYEN_NGAY"
export const DELETE_UNG_TUYEN_NGAY_SUCCESS = "DELETE_UNG_TUYEN_NGAY_SUCCESS"
export const DELETE_UNG_TUYEN_NGAY_FAIL = "DELETE_UNG_TUYEN_NGAY_FAIL"

// export const UPDATE_UNG_TUYEN_NGAY = "UPDATE_UNG_TUYEN_NGAY"
// export const UPDATE_UNG_TUYEN_NGAY_SUCCESS = "UPDATE_UNG_TUYEN_NGAY_SUCCESS"
// export const UPDATE_UNG_TUYEN_NGAY_FAIL = "UPDATE_UNG_TUYEN_NGAY_FAIL"

export const SEARCH_UNG_TUYEN_NGAY = "SEARCH_UNG_TUYEN_NGAY"
export const SEARCH_UNG_TUYEN_NGAY_SUCCESS = "SEARCH_UNG_TUYEN_NGAY_SUCCESS"
export const SEARCH_UNG_TUYEN_NGAY_FAIL = "SEARCH_UNG_TUYEN_NGAY"



