export const GET_HINH_THUC_UNG_TUYEN = "GET_HINH_THUC_UNG_TUYEN"
export const GET_HINH_THUC_UNG_TUYEN_SUCCESS = "GET_HINH_THUC_UNG_TUYEN_SUCCESS"
export const GET_HINH_THUC_UNG_TUYEN_FAIL = "GET_HINH_THUC_UNG_TUYEN_FAIL"

export const ADD_HINH_THUC_UNG_TUYEN = "ADD_HINH_THUC_UNG_TUYEN"
export const ADD_HINH_THUC_UNG_TUYEN_SUCCESS = "ADD_HINH_THUC_UNG_TUYEN_SUCCESS"
export const ADD_HINH_THUC_UNG_TUYEN_FAIL = "ADD_HINH_THUC_UNG_TUYEN_FAIL"

export const DELETE_HINH_THUC_UNG_TUYEN = "DELETE_HINH_THUC_UNG_TUYEN"
export const DELETE_HINH_THUC_UNG_TUYEN_SUCCESS = "DELETE_HINH_THUC_UNG_TUYEN_SUCCESS"
export const DELETE_HINH_THUC_UNG_TUYEN_FAIL = "DELETE_HINH_THUC_UNG_TUYEN_FAIL"

export const UPDATE_HINH_THUC_UNG_TUYEN = "UPDATE_HINH_THUC_UNG_TUYEN"
export const UPDATE_HINH_THUC_UNG_TUYEN_SUCCESS = "UPDATE_HINH_THUC_UNG_TUYEN_SUCCESS"
export const UPDATE_HINH_THUC_UNG_TUYEN_FAIL = "UPDATE_HINH_THUC_UNG_TUYEN_FAIL"

export const SEARCH_HINH_THUC_UNG_TUYEN = "SEARCH_HINH_THUC_UNG_TUYEN"
export const SEARCH_HINH_THUC_UNG_TUYEN_SUCCESS = "SEARCH_HINH_THUC_UNG_TUYEN_SUCCESS"
export const SEARCH_HINH_THUC_UNG_TUYEN_FAIL = "SEARCH_HINH_THUC_UNG_TUYEN"



