export const GET_VI_TRI_UNG_TUYEN = "GET_VI_TRI_UNG_TUYEN"
export const GET_VI_TRI_UNG_TUYEN_SUCCESS = "GET_VI_TRI_UNG_TUYEN_SUCCESS"
export const GET_VI_TRI_UNG_TUYEN_FAIL = "GET_VI_TRI_UNG_TUYEN_FAIL"

export const ADD_VI_TRI_UNG_TUYEN = "ADD_VI_TRI_UNG_TUYEN"
export const ADD_VI_TRI_UNG_TUYEN_SUCCESS = "ADD_VI_TRI_UNG_TUYEN_SUCCESS"
export const ADD_VI_TRI_UNG_TUYEN_FAIL = "ADD_VI_TRI_UNG_TUYEN_FAIL"

export const DELETE_VI_TRI_UNG_TUYEN = "DELETE_VI_TRI_UNG_TUYEN"
export const DELETE_VI_TRI_UNG_TUYEN_SUCCESS = "DELETE_VI_TRI_UNG_TUYEN_SUCCESS"
export const DELETE_VI_TRI_UNG_TUYEN_FAIL = "DELETE_VI_TRI_UNG_TUYEN_FAIL"

export const UPDATE_VI_TRI_UNG_TUYEN = "UPDATE_VI_TRI_UNG_TUYEN"
export const UPDATE_VI_TRI_UNG_TUYEN_SUCCESS = "UPDATE_VI_TRI_UNG_TUYEN_SUCCESS"
export const UPDATE_VI_TRI_UNG_TUYEN_FAIL = "UPDATE_VI_TRI_UNG_TUYEN_FAIL"

export const SEARCH_VI_TRI_UNG_TUYEN = "SEARCH_VI_TRI_UNG_TUYEN"
export const SEARCH_VI_TRI_UNG_TUYEN_SUCCESS = "SEARCH_VI_TRI_UNG_TUYEN_SUCCESS"
export const SEARCH_VI_TRI_UNG_TUYEN_FAIL = "SEARCH_VI_TRI_UNG_TUYEN"



