export const GET_SINH_VIEN_TUYEN_DUNG = "GET_SINH_VIEN_TUYEN_DUNG"
export const  GET_SINH_VIEN_TUYEN_DUNG_SUCCESS = "GET_SINH_VIEN_TUYEN_DUNG_SUCCESS"
export const GET_SINH_VIEN_TUYEN_DUNG_FAIL = "GET_SINH_VIEN_TUYEN_DUNG_FAIL"

export const ADD_SINH_VIEN_TUYEN_DUNG = "ADD_SINH_VIEN_TUYEN_DUNG"
export const ADD_SINH_VIEN_TUYEN_DUNG_SUCCESS = "ADD_SINH_VIEN_TUYEN_DUNG_SUCCESS"
export const ADD_SINH_VIEN_TUYEN_DUNG_FAIL = "ADD_SINH_VIEN_TUYEN_DUNG_FAIL"

export const DELETE_SINH_VIEN_TUYEN_DUNG = "DELETE_SINH_VIEN_TUYEN_DUNG"
export const DELETE_SINH_VIEN_TUYEN_DUNG_SUCCESS = "DELETE_SINH_VIEN_TUYEN_DUNG_SUCCESS"
export const DELETE_SINH_VIEN_TUYEN_DUNG_FAIL = "DELETE_SINH_VIEN_TUYEN_DUNG_FAIL"

export const UPDATE_SINH_VIEN_TUYEN_DUNG = "UPDATE_SINH_VIEN_TUYEN_DUNG"
export const UPDATE_SINH_VIEN_TUYEN_DUNG_SUCCESS = "UPDATE_SINH_VIEN_TUYEN_DUNG_SUCCESS"
export const UPDATE_SINH_VIEN_TUYEN_DUNG_FAIL = "UPDATE_SINH_VIEN_TUYEN_DUNG_FAIL"

export const SEARCH_SINH_VIEN_TUYEN_DUNG = "SEARCH_SINH_VIEN_TUYEN_DUNG"
export const SEARCH_SINH_VIEN_TUYEN_DUNG_SUCCESS = "SEARCH_SINH_VIEN_TUYEN_DUNG_SUCCESS"
export const SEARCH_SINH_VIEN_TUYEN_DUNG_FAIL = "SEARCH_SINH_VIEN_TUYEN_DUNG"



