export const GET_CHI_TIET_TUYEN_DUNG = "GET_CHI_TIET_TUYEN_DUNG"
export const GET_CHI_TIET_TUYEN_DUNG_SUCCESS = "GET_CHI_TIET_TUYEN_DUNG_SUCCESS"
export const GET_CHI_TIET_TUYEN_DUNG_FAIL = "GET_CHI_TIET_TUYEN_DUNG_FAIL"
