export const GET_KHOA = "GET_KHOA"
export const GET_KHOA_SUCCESS = "GET_KHOA_SUCCESS"
export const GET_KHOA_FAIL = "GET_KHOA_FAIL"

// 
export const ADD_KHOA = "ADD_KHOA"
export const ADD_KHOA_SUCCESS = "ADD_KHOA_SUCCESS"
export const ADD_KHOA_FAIL = "ADD_KHOA_FAIL"

// 
export const DELETE_KHOA = "DELETE_KHOA"
export const DELETE_KHOA_SUCCESS = "DELETE_KHOA_SUCCESS"
export const DELETE_KHOA_FAIL = "DELETE_KHOA_FAIL"

// export const UPDATE_KHOA = "UPDATE_KHOA"
// export const UPDATE_KHOA_SUCCESS = "UPDATE_KHOA_SUCCESS"
// export const UPDATE_KHOA_FAIL = "UPDATE_KHOA_FAIL"

// 
export const SEARCH_KHOA = "SEARCH_KHOA"
export const SEARCH_KHOA_SUCCESS = "SEARCH_KHOA_SUCCESS"
export const SEARCH_KHOA_FAIL = "SEARCH_KHOA"

// 
export const GET_KHOA_FILTER = "GET_KHOA_FILTER"
export const GET_KHOA_FILTER_SUCCESS = "GET_KHOA_FILTER_SUCCESS"
export const GET_KHOA_FILTER_FAIL = "GET_KHOA_FILTER_FAIL"

// 
export const GET_ALL_KHOA_FILTER = "GET_ALL_KHOA_FILTER"
export const GET_ALL_KHOA_FILTER_SUCCESS = "GET_ALL_KHOA_FILTER_SUCCESS"
export const GET_ALL_KHOA_FILTER_FAIL = "GET_ALL_KHOA_FILTER_FAIL"

// 
export const POST_KHOA_FILTER = "POST_KHOA_FILTER"
export const POST_KHOA_FILTER_SUCCESS = "POST_KHOA_FILTER_SUCCESS"
export const POST_KHOA_FILTER_FAIL = "POST_KHOA_FILTER_FAIL"










