export const GET_CAM_KET_TUYEN_DUNG = "GET_CAM_KET_TUYEN_DUNG"
export const GET_CAM_KET_TUYEN_DUNG_SUCCESS = "GET_CAM_KET_TUYEN_DUNG_SUCCESS"
export const GET_CAM_KET_TUYEN_DUNG_FAIL = "GET_CAM_KET_TUYEN_DUNG_FAIL"

export const ADD_CAM_KET_TUYEN_DUNG = "ADD_CAM_KET_TUYEN_DUNG"
export const ADD_CAM_KET_TUYEN_DUNG_SUCCESS = "ADD_CAM_KET_TUYEN_DUNG_SUCCESS"
export const ADD_CAM_KET_TUYEN_DUNG_FAIL = "ADD_CAM_KET_TUYEN_DUNG_FAIL"

export const DELETE_CAM_KET_TUYEN_DUNG = "DELETE_CAM_KET_TUYEN_DUNG"
export const DELETE_CAM_KET_TUYEN_DUNG_SUCCESS = "DELETE_CAM_KET_TUYEN_DUNG_SUCCESS"
export const DELETE_CAM_KET_TUYEN_DUNG_FAIL = "DELETE_CAM_KET_TUYEN_DUNG_FAIL"

export const UPDATE_CAM_KET_TUYEN_DUNG = "UPDATE_CAM_KET_TUYEN_DUNG"
export const UPDATE_CAM_KET_TUYEN_DUNG_SUCCESS = "UPDATE_CAM_KET_TUYEN_DUNG_SUCCESS"
export const UPDATE_CAM_KET_TUYEN_DUNG_FAIL = "UPDATE_CAM_KET_TUYEN_DUNG_FAIL"

export const SEARCH_CAM_KET_TUYEN_DUNG = "SEARCH_CAM_KET_TUYEN_DUNG"
export const SEARCH_CAM_KET_TUYEN_DUNG_SUCCESS = "SEARCH_CAM_KET_TUYEN_DUNG_SUCCESS"
export const SEARCH_CAM_KET_TUYEN_DUNG_FAIL = "SEARCH_CAM_KET_TUYEN_DUNG"



